name: Code Gen From OpenAPI Spec

on:
  repository_dispatch:
    types: [update-open-api-spec]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  # gh_token: ${{ secrets.IOS_TEAM_PAT }} # IOS_TEAM_PAT: project, read:org, repo
  # iOS
  ios_repo: suguruTakahashi-1234/swift-openapi-gen-sample
  ios_openapi_path: schema/openapi.yaml
  # Server Side
  server_side_repo: suguruTakahashi-1234/swift-openapi-gen-sample
  server_side_openapi_path: server-side-repository/openapi.yaml

jobs:
  code-gen-from-open-api-spec:
    # Ref: https://github.com/actions/runner-images
    runs-on: macos-14
    env:
      # Ref: https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    timeout-minutes: 300

    steps:
    - name: Checkout iOS repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.ios_repo }}
        path: ios-repo
        # token: ${{ env.gh_token }}

    - name: Checkout Server Side repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.server_side_repo }}
        path: server-repo
        ref: ${{ github.event.client_payload.ref || 'refs/heads/main' }}
        # token: ${{ env.gh_token }}

    - name: Check for differences in OpenAPI spec
      id: check_diff
      run: |
        if diff server-repo/${{ env.server_side_openapi_path }} ios-repo/${{ env.ios_openapi_path }}; then
          echo "changes_detected=false" >> $GITHUB_OUTPUT
          echo "No changes in OpenAPI spec. Exiting."
          exit 0
        else
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "Changes detected in OpenAPI spec. Proceeding with code generation."
          cp -f server-repo/${{ env.server_side_openapi_path }} ios-repo/${{ env.ios_openapi_path }}
        fi

    - name: Generate code from OpenAPI spec
      if: steps.check_diff.outputs.changes_detected == 'true'
      run: |
        make -C ios-repo open-api-gen
        git -C ios-repo status
        git -C ios-repo diff

    - name: Create Pull Request
      if: steps.check_diff.outputs.changes_detected == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        # token: ${{ secrets.IOS_TEAM_PAT }}
        commit-message: 【OpenAPI】Update generated code from OpenAPI spec [ci skip]
        branch: feature/code-gen-from-open-api-spec
        title: 【OpenAPI】Update generated code from OpenAPI spec
        body: This PR updates the generated code from the latest OpenAPI spec.
        labels: "enhancement"
        path: ios-repo
